:: ============================================================================
:: STAR WARS: Empire at War - Forces of Corruption Unofficial Patch Tool
:: Original Author: jsuzu (Discord: @AlyMar1994)
::			Author: jsuzu (Discord: @AlyMar1994)
::			Date:   09-26-2026
::		Revision:   2
:: ============================================================================
:: Builds all TXT language files in the current directory into DAT.
:: Also deletes possible build log generated by Jorrit's DAT Assembler.

__datassembler_v2.exe /b MasterTextFile_ENGLISH.txt MasterTextFile_ENGLISH.dat
__datassembler_v2.exe /b MasterTextFile_FRENCH.txt MasterTextFile_FRENCH.dat
__datassembler_v2.exe /b MasterTextFile_GERMAN.txt MasterTextFile_GERMAN.dat
__datassembler_v2.exe /b MasterTextFile_ITALIAN.txt MasterTextFile_ITALIAN.dat
__datassembler_v2.exe /b MasterTextFile_JAPANESE.txt MasterTextFile_JAPANESE.dat
__datassembler_v2.exe /b MasterTextFile_POLISH.txt MasterTextFile_POLISH.dat
__datassembler_v2.exe /b MasterTextFile_RUSSIAN.txt MasterTextFile_RUSSIAN.dat
__datassembler_v2.exe /b MasterTextFile_SPANISH.txt MasterTextFile_SPANISH.dat
del /f /q buildlog.txt
