:: ============================================================================
:: STAR WARS: Empire at War - Forces of Corruption Unofficial Patch Tool
:: Original Author: jsuzu (Discord: @AlyMar1994)
::			Author: jsuzu (Discord: @AlyMar1994)
::			Date:   09-26-2026
::		Revision:   2
:: ============================================================================
:: Alphabetizes all strings in all TXT language files in the current directory.
:: Also deletes possible build log generated by Jorrit's DAT Assembler.

__datassembler_v2.exe /a MasterTextFile_ENGLISH.txt
__datassembler_v2.exe /a MasterTextFile_FRENCH.txt
__datassembler_v2.exe /a MasterTextFile_GERMAN.txt
__datassembler_v2.exe /a MasterTextFile_ITALIAN.txt
__datassembler_v2.exe /a MasterTextFile_JAPANESE.txt
__datassembler_v2.exe /a MasterTextFile_POLISH.txt
__datassembler_v2.exe /a MasterTextFile_RUSSIAN.txt
__datassembler_v2.exe /a MasterTextFile_SPANISH.txt
del /f /q buildlog.txt
