name: Bug Report
description: Help us eliminate bugs in Forces of Corruption, or in the Patch.  This is the generic bug template, please choose a more specific template *if* the issue can be narrowed down.
title: "Example: UNIT - QUICK DESCRIPTION"
labels: ["Bug (FoC)"]
projects: [""]
assignees:
  - AlyMar1994
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please quickly search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this report!!  Please fill out everything, do your best.  One of the repo's maintainers will fix edit the report's attributes should something be wrong and clarify in the comments.
  - type: input
    id: contact
    attributes:
      label: Contact Details - Discord (optional)
      description: If you're in the Empire at War Community Hub, please write down your username/server nickname to be quickly contacted if something's needed.  This is completely optional, otherwise only the report's comments will be used.
      placeholder: ex. alymar1994
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: FoC Version
      description: What version of Forces of Corruption are you running?  (Version can be seen in the main menu, at the bottom-left.)
      options:
        - 1.121.859328 (2024)
        - 1.121.826596 (11/20/23, 64-bit)
        - 1.121.748742 (11/09/22)
        - Other (Unknown)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: UFoCP Version
      description: What version of the Unofficial Patch are you running?  (If you are at all.)
      options:
        - N/A (W/O Patch)
        - 2.0.0.XXXX
        - 1.16.682
        - Other (Older)
      default: 0
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Please write, in detail, what happened.  Fill out the provided prompt.  Please don't be superfluous, we need info but not how hard you sneezed 2 hours into your gameplay session.  FoC's game version can be found on the main menu, at the bottom-left in blue text.
      placeholder: Tell us what you see!
      value: |
        **Quick Information**
        _OS:_
        _GPU:_
        _CPU:_
        _List any other mods used:_ v
        _Were you playing on Steam?_ YES/NO
        _Were you in multiplayer?_ YES/NO

        **Explain the Issue:**

        **Steps to Reproduce Issue:**
        1.
        2.
        3. ...

        **Screenshots/Videos:**
    validations:
      required: true
  - type: textarea
    id: possible-cause
    attributes:
      label: Possible Cause
      description: Please write why you think this is a bug in either FoC/UFoCP.  This section will not invalidate your bug report - it's just a personal justification on why this report should be fixed.
      placeholder: who knows
      value: "Maybe a Content Designer (CD) was forgetful?"
