name: Crash
description: Help us eliminate as many crashes as we can within FoC or UFoCP.  This template encompasses all types of crashes - white-screen, crash reporter, hard-close (close w/o crash reporter), etc.
title: "Example: Crash - Description of Crash Situation"
labels: ["Crash"]
projects: [""]
assignees:
  - AlyMar1994
body:
  - type: markdown
    attributes:
      value: |
        -=-=-=-=-=-
        This reporting template is for crashes that happen for any reason in FoC or UFoCP.  To fully submit a crash report, you must download the Debugging Client from the issue template selection page, and use it to generate debug logs in your Forces of Corruption directory.  Place the executables next to the game's application in the ..\corruption\ folder.  If you cannot generate a log for any reason (e.g. if the crash isn't easily reproducable), then explain the crash as vividly and detail-full as you can when, where, and what you were doing when it happened.  To acknowledge you read this, delete this bloc, otherwise your report will be immediately closed and disregarded.
        -=-=-=-=-=-
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?  And did you read the above paragraph?
      description: Please quickly search to see if an issue already exists for the bug you encountered.  After reading the above paragraph, check the box.
      options:
        - label: I have searched the existing issues
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details - Discord (optional)
      description: If you're in the Empire at War Community Hub, please write down your username/server nickname to be quickly contacted if something's needed.  This is completely optional, otherwise only the report's comments will be used.
      placeholder: ex. alymar1994
    validations:
      required: false
  - type: dropdown
    id: versionfoc
    attributes:
      label: FoC Version
      description: What version of Forces of Corruption are you running?  (Version can be seen in the main menu, at the bottom-left.)
      options:
        - 1.121.859328 (2024)
        - 1.121.826596 (11/20/23, 64-bit)
        - 1.121.748742 (11/09/22)
        - Other (Unknown)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: versionufocp
    attributes:
      label: UFoCP Version
      description: What version of the Unofficial Patch are you running?  (If you are at all.)
      options:
        - N/A (W/O Patch)
        - 2.0.0.XXXX
        - 1.16.682
        - Other (Older)
      default: 0
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What Happened?
      description: Please write, in detail, what happened.  Fill out the provided prompt.  Please don't be superfluous, we need info but not how hard you sneezed 2 hours into your gameplay session.  Please include images or video in this prompt, if possible.
      placeholder: Don't forget this!
      value: |
        **Explain the Issue:**


        **Screenshots/Video:**
    validations:
      required: true
  - type: textarea
    id: pc-specs
    attributes:
      label: PC Specs
      description: Your PC specs and game state may be important regarding this bug.  Please note them here.
      placeholder: Don't forget this!
      value: |
        **Quick Information:**
        _OS:_
        _GPU:_
        _CPU:_
        _List any other mods used:_ 
        _Were you playing on Steam?_ YES/NO
        _Were you in multiplayer?_ YES/NO
        _Game Language:_ 
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Steps to Reproduce
      description: Please note consistent steps to reproduce this bug, if possible.
      placeholder: Don't forget this!
      value: |
        **Steps to Reproduce:**
        1. 
        2. 
        3. ...
    validations:
      required: false
  - type: textarea
    id: possiblecause
    attributes:
      label: Possible Cause
      description: Please write why you think this is a bug in either FoC/UFoCP.  This section will not invalidate your bug report - it's just a personal justification on why this report should be fixed.
      placeholder: who knows
      value: "Maybe a Content Designer (CD) was forgetful?"
    validations:
      required: false
  - type: textarea
    id: logfiles
    attributes:
      label: Debugger Log Files
      description: Please compile all of your generated log files (if you have them) into a .7z/ZIP, and send them here.  After running the debugger, you should have: _Audio_Drivers, _GraphicsInit, _LogFile, _MemLog, _Missing_Text, _warn_message_popup, AILog and StoryLog.
      placeholder: Don't forget this!
      value: "Awaiting upload...."
    validations:
      required: false
  - type: textarea
    id: save
    attributes:
      label: Save Game
      description: If you have a save right before a crash, please provide it here.  Saved games can be found in ..\Users\USERNAME\Saved Games\Petroglyph\Empire At War - Forces of Corruption\save\.
      placeholder: Don't forget this!
      value: "Awaiting upload...."
    validations:
      required: false
