name: Suggestion
description: Suggest a change with how UFoCP handles a fix.
title: "Example: UNIT - QUICK DESCRIPTION"
labels: ["Suggestion"]
projects: [""]
assignees:
  - AlyMar1994
body:
  - type: markdown
    attributes:
      value: |
        -=-=-=-=-=-
        This may be different compared to a normal report, relating to something considered good, fully fixed or an improvement in methods used for the Patch.
        -=-=-=-=-=-
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please quickly search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details - Discord (optional)
      description: If you're in the Empire at War Community Hub, please write down your username/server nickname to be quickly contacted if something's needed.  This is completely optional, otherwise only the report's comments will be used.
      placeholder: ex. alymar1994
    validations:
      required: false
  - type: dropdown
    id: versionfoc
    attributes:
      label: FoC Version
      description: What version of Forces of Corruption are you running?  (Version can be seen in the main menu, at the bottom-left.)
      options:
        - 1.121.859328 (10/22/24)
        - 1.121.826596 (11/20/23, 64-bit)
        - 1.121.748742 (11/09/22)
        - Other (Unknown)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: versionufocp
    attributes:
      label: UFoCP Version
      description: What version of the Unofficial Patch are you running?  (If you are at all.)
      options:
        - N/A (W/O Patch)
        - 2.0.0.XXXX
        - 1.16.682
        - Other (Older)
      default: 0
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Description of Suggestion
      description: Please write, in detail, what you think should be changed.  Fill out the provided prompt.  Please don't be superfluous.
      placeholder: Don't forget this!
      value: |
        **Explain the Suggestion:**
    validations:
      required: true
  - type: textarea
    id: possiblecause
    attributes:
      label: Reasoning for Suggestion
      description: Please write your reasoning for this suggestion.
      placeholder: who knows
      value: "Well..."
    validations:
      required: true
