blank_issues_enabled: false
contact_links:
  - name: Advanced Info - Debug Client
    url: https://www.petroglyphgames.com/eawmodtool/
    about: For quick access to the debugging client to generate debug logs when necessary.