blank_issues_enabled: false
contact_links:
  - name: ADV. INFO: Debugger
    url: https://www.petroglyphgames.com/eawmodtool/
    about: Quick access to the debugging client to generate debug logs when necessary.